language: ruby
os:
- linux
- osx
- windows
  language: bash
  install:
    - choco install mingw
    - choco install msys2
    - ridk.cmd exec pacman -S --noconfirm --needed base-devel mingw-w64-x86_64-toolchain
rvm:
- 2.3.0
- 2.4.0
- 2.5.0
- 2.6.0
- 2.7.0
bundler_args: --jobs=2
script:
- bundle exec rspec
cache: bundler

